### ISSUE TITLE
用golang重写可能吗

### ISSUE THREAD

**Issue by passerbyo** [encoderlee/android_tools#2]

**Comment by encoderlee** [comment]
这个东西从原理上来说只是个文本处理工具，处理逻辑就是找到每个.method开头的函数，在下面一行插入
'    invoke-static {}, Lcom/hook/tools/InjectLog;->PrintCaller()V\n'
这串文本，就完了。用什么语言写都可以的，不过我对golang不熟悉，这个事情可能需要golang方面的人士来处理了
